name: Checks
on: [push, pull_request]
jobs:
  rust:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: make check
      - run: cargo test --locked
      - run: make package
